baseURL = 'https://dev.technasium.funmetjoel.nl/'
title = 'Technasium'

[author]
    name = ['Joël Rodenbach', 'Docenten']

[params]
    title = 'Technasium'
    description = 'Technasium'
    keywords = 'Technasium'
    custom_css = ["css/main.css", "css/headerstyle.css", "css/footerstyle.css", "css/home.css", "css/vaardigheidStyle.css", "css/liststyle.css"]
    custom_js = ["js/header.js", "js/custom.js"]
    GitHubLink = 'https://github.com/FunMetJoel/TechnasiumSite/tree/hugo/content'



[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
